// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations require a direct Postgres URL; the app uses DATABASE_URL (Accelerate) at runtime.
    url: env("DIRECT_DATABASE_URL"),
  },
});
